"""add workspace project columns

Revision ID: f4221efef687
Revises: eef2fdebb60a
Create Date: 2026-06-07 20:11:38.052793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4221efef687"
down_revision: Union[str, Sequence[str], None] = "eef2fdebb60a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_tasks_id"), table_name="agent_tasks")
    op.drop_table("agent_tasks")
    op.add_column("workspaces", sa.Column("project_ref", sa.String(), nullable=True))
    op.add_column("workspaces", sa.Column("project_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "project_name")
    op.drop_column("workspaces", "project_ref")
    op.create_table(
        "agent_tasks",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("status", sa.VARCHAR(), nullable=True),
        sa.Column("task_desc", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_tasks_id"), "agent_tasks", ["id"], unique=False)
    # ### end Alembic commands ###
